# GitHub Action for generating a contribution graph with a snake eating your contributions.
# Original repo: https://github.com/Platane/snk


name: Generate Snake

# Controls when the action will run. This action runs every 30 minutes.

on:
  push:
    branches:
      - main
  schedule:
      # every 30 minutes
    - cron: "*/30 * * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks repo, so your job can access it
      - uses: actions/checkout@v2
      
    # Generates the snake  
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # these next 2 lines generate the files inside a folder called "output".
          gif_out_path: output/github-contribution-grid-snake.gif
          svg_out_path: output/github-contribution-grid-snake.svg        
    
    # Adds and commits the files
      - name: Commit files
        run: |
          git config --local user.email "prabs.shrestha@gmail.com"
          git config --local user.name "prabsshrestha"
          git status
          git add .
          git commit -m "Created snake gif and svg"
          
      # Push the changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
